## Numpy Fundamentals

### 📝 Array Creation 

In [4]:
# Creating NumPy Array: np.Array()
import numpy as np

#list
arr_list = np.array([1,2,3,4,5,6,7,8,9])
print(arr_list)

#tuple
arr_tuple = np.array((1,2,3,4,5))
print(arr_tuple)

#2D
arr_list2D = np.array([[1,2],[3,4]])
print(arr_list2D)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[[1 2]
 [3 4]]


In [5]:
# Creating NumPy Array with Data Type
arr1 = np.array([1,2,3,4,5,6,7,8,9], dtype = "float64")
arr1


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
# Creating NumPy Array using np.Arange() and reshape()
arr = np.arange(1,22)
arr

arr2= np.arange(1,11).reshape(2,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
# np.ones and np.zeros
arr = np.ones(5)
arr
print(arr)
arr2= np.zeros((4,4))
arr2

[1. 1. 1. 1. 1.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# np.random
arr = np.random.random(6)
arr
arr2 = np.random.random((2,5))
arr2


array([[3.37743153e-02, 8.56879565e-01, 8.12666866e-01, 9.03809014e-04,
        2.80143958e-01],
       [7.10876369e-01, 9.28288810e-01, 8.22319940e-02, 3.46716645e-01,
        3.02365885e-01]])

In [21]:
# linearly spaced array- np.linspace()
arr = np.linspace(1,100,10)
arr


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
# Identity Matrix Creation 
arr = np.ones((2,2))
arr


array([[1., 1.],
       [1., 1.]])

In [33]:
# NumPy Attributes (dtype, size, shape, itemsize, ndim)
arr = np.array([[3,34]])
print(arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)
print(arr.astype(float))



int32
2
(1, 2)
2
4
[[ 3. 34.]]


In [34]:
# Changing Datatype - astype
arr = np.array([3,4])
print(arr.astype(float))


[3. 4.]


### 📝 NumPy Array Functions

In [35]:
# Max/Min/Sum/Prod
arr=np.array([2,3,4,4])
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.prod())


4
2
13
96


In [36]:
#  Mean, Standard Deviation, Variance 
arr=np.array([2,4,563,63,53,5])
print(arr.mean())
print(arr.std())
print(arr.var())



115.0
201.84234772052503
40740.333333333336


In [38]:
# Arrays Dot Product
arr1 = np.arange(1,13).reshape((3,4))
arr2 = np.arange(12,24).reshape((4,3))
print(np.dot(arr1,arr2))




[[180 190 200]
 [444 470 496]
 [708 750 792]]


In [40]:
# Log and Exp function
arr=np.array([2,3,556,3])
print(np.log(arr))
print(np.exp(arr))


[0.69314718 1.09861229 6.32076829 1.09861229]
[7.38905610e+000 2.00855369e+001 2.93583699e+241 2.00855369e+001]


In [ ]:
# Round, Floor, Ceil
arr = np.array([1.37, 2.56, 3.89, 4.12, 5.75])
print(np.round(arr, 1))
print(np.floor(arr))
print(np.ceil(arr))

In [64]:
# Indexing Slicing (Already Covered in Lecture in depth)
arr1 = np.arange(10)
arr2 = np.arange(12).reshape((3,4))
arr3 = np.arange(8).reshape((2,2,2))
print(arr1)
print(arr2)
print(arr3)
print(arr1[1:4])
print(arr2[1:2,0:3])
print(arr3[0:1,0:1,0:1])

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[1 2 3]
[[4 5 6]]
[[[0]]]


In [ ]:
# reshape
arr = np.arange(1, 13)
print("Original:", arr)
arr_reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", arr_reshaped)

In [ ]:
# Transpose
arr = np.arange(1, 13).reshape(3, 4)
print("Original:\n", arr)
print("Transposed:\n", arr.T)

In [ ]:
# ravel or flatten
arr = np.arange(1, 13).reshape(3, 4)
print("Original:\n", arr)
print("Ravel:", arr.ravel())
print("Flatten:", arr.flatten())

In [ ]:
# Stacking - horizontal Stacking
arr1 = np.arange(0, 12).reshape((3, 4))
arr2 = np.arange(12, 24).reshape((3, 4))
print(np.hstack((arr1, arr2)))

In [ ]:
# Vertical Stacking
arr1 = np.arange(0, 12).reshape((3, 4))
arr2 = np.arange(12, 24).reshape((3, 4))
print(np.vstack((arr1, arr2)))

In [ ]:
# Splitting - Vertical Splitting
arr1 = np.arange(0, 16).reshape((4, 4))
print("Original:\n", arr1)
result = np.vsplit(arr1, 2)
print("Part 1:\n", result[0])
print("Part 2:\n", result[1])

In [ ]:
# Horizontal Splitting
arr1 = np.arange(0, 16).reshape((4, 4))
print("Original:\n", arr1)
result = np.hsplit(arr1, 2)
print("Part 1:\n", result[0])
print("Part 2:\n", result[1])

In [ ]:
# Understanding Views (shares memory - changes reflect in original)
arr = np.arange(1, 6)
view = arr.view()
view[0] = 99
print("Original after view change:", arr)
print("View:", view)

In [ ]:
# Understanding Copies (independent - changes do NOT reflect in original)
arr = np.arange(1, 6)
copy = arr.copy()
copy[0] = 99
print("Original after copy change:", arr)
print("Copy:", copy)

### 📝 Challenging Section 

#### 1. Create a vector of zeros of size 10 but the fifth value should be 1.

In [ ]:
# Code here
arr = np.zeros(10)
arr[4] = 1
print(arr)

#### 2. Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) <br> and print the array and avg of the array.





In [ ]:
# Code here
a = int(input("Enter number of rows (a): "))
b = int(input("Enter number of columns (b): "))
arr = np.random.random((a, b))
print("Array:\n", arr)
print("Average:", arr.mean())

#### 3. Create a 2d array with 1 on the border and 0 inside. 

In [ ]:
# Code here
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
print(arr)

#### 4. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
# Code here
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

#### 5. Can you create a identity mattrix of shape (3,4). If yes write code for it

In [ ]:
# Code here
# A true identity matrix must be square, so (3,4) is not possible.
# But we can create a rectangular matrix with 1s on the diagonal using np.eye:
arr = np.eye(3, 4)
print(arr)

#### 6. Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
# Code here
arr = np.tile(np.arange(0, 5), (5, 1))
print(arr)

#### 7. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# Code here (100th element = index 99)
print(np.unravel_index(99, (6, 7, 8)))

#### 8. Provided a numpy array, your task is to print a reversed NumPy array with the element type float.

In [ ]:
# Code here
arr = np.arange(5)
reversed_arr = arr[::-1].astype(float)
print(reversed_arr)

#### 9. Count the number of elements of a numpy array.

In [ ]:
# Code here
arr = np.arange(12).reshape(3, 4)
print("Array:\n", arr)
print("Number of elements:", arr.size)

#### 10. Write a python function that accepts infinite number of numpy arrays <br> and do the vertical stack to them. Then return that new array as result.

In [ ]:
# Code here
def vstack_arrays(*arrays):
    return np.vstack(arrays)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print(vstack_arrays(a, b, c))

#### 11. Swap column-1 of array with column-2 in the array.

In [ ]:
# Code here
arr = np.arange(9).reshape(3, 3)
print("Original:\n", arr)
arr[:, [0, 1]] = arr[:, [1, 0]]
print("After swapping col-1 and col-2:\n", arr)

#### 12. Replace odd elements in arrays with -1.

In [ ]:
# Code here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

#### 13.  Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [ ]:
# Code here
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])
print(np.maximum(a, b))

#### 14. Write a function which will accept 2 arguments.

In [ ]:
# Code here
def nth_largest(arr, n):
    sorted_arr = np.sort(arr)[::-1]
    return sorted_arr[n - 1]

print(nth_largest(np.array([12, 34, 40, 7, 1, 0]), 3))  # 12
print(nth_largest(np.array([12, 34, 40, 7, 1, 0]), 1))  # 40

#### 15. Create the following pattern without hardcoding. 

In [ ]:
# Code here
a = np.array([1, 2, 3])
result = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print(result)

#### 16. Create a python function named date_array that accepts two dates as string format <br> and returns a numpy array of dates between those 2 dates. The function only accept 2 strings.

In [ ]:
# Code here
def date_array(start, end):
    return np.arange(start, end, dtype='datetime64[D]')

print(date_array('2022-12-01', '2022-12-06'))

**Happy Coding 🎉🎉**